### PR TITLE
WIP: use DSA with aruba ap303h

### PR DESCRIPTION
**Pull request by yogo1212**
this is basically a blindfolded attempt. i've got no knowledge about the board.
@kroon040 is going to test the build.

<details><summary>swconfig and board.json supplied by kroon040</summary>
<p>

```
root@OpenWrt:/# swconfig dev switch0 show
Global attributes:
        enable_vlan: 1
        enable_mirror_rx: 0
        enable_mirror_tx: 0
        mirror_monitor_port: 0
        mirror_source_port: 0
        linkdown: ???
Port 0:
        mib: Port 0 MIB counters
RxBroad     : 6
RxPause     : 0
RxMulti     : 36
RxFcsErr    : 0
RxAlignErr  : 0
RxRunt      : 0
RxFragment  : 0
Rx64Byte    : 3
Rx128Byte   : 45
Rx256Byte   : 21
Rx512Byte   : 3
Rx1024Byte  : 0
Rx1518Byte  : 2
RxMaxByte   : 0
RxTooLong   : 0
RxGoodByte  : 11282
RxBadByte   : 0
RxOverFlow  : 0
Filtered    : 23
TxBroad     : 146
TxPause     : 0
TxMulti     : 5481
TxUnderRun  : 0
Tx64Byte    : 82
Tx128Byte   : 251
Tx256Byte   : 997
Tx512Byte   : 2686
Tx1024Byte  : 1525
Tx1518Byte  : 114
TxMaxByte   : 0
TxOverSize  : 0
TxByte      : 2415131
TxCollision : 0
TxAbortCol  : 0
TxMultiCol  : 0
TxSingleCol : 0
TxExcDefer  : 0
TxDefer     : 0
TxLateCol   : 0

        pvid: 2
        link: port:0 link:up speed:1000baseT full-duplex txflow rxflow
Port 1:
        mib: Port 1 MIB counters
RxBroad     : 0
RxPause     : 0
RxMulti     : 0
RxFcsErr    : 0
RxAlignErr  : 0
RxRunt      : 0
RxFragment  : 0
Rx64Byte    : 0
Rx128Byte   : 0
Rx256Byte   : 0
Rx512Byte   : 0
Rx1024Byte  : 0
Rx1518Byte  : 0
RxMaxByte   : 0
RxTooLong   : 0
RxGoodByte  : 0
RxBadByte   : 0
RxOverFlow  : 0
Filtered    : 0
TxBroad     : 0
TxPause     : 0
TxMulti     : 0
TxUnderRun  : 0
Tx64Byte    : 0
Tx128Byte   : 0
Tx256Byte   : 0
Tx512Byte   : 0
Tx1024Byte  : 0
Tx1518Byte  : 0
TxMaxByte   : 0
TxOverSize  : 0
TxByte      : 0
TxCollision : 0
TxAbortCol  : 0
TxMultiCol  : 0
TxSingleCol : 0
TxExcDefer  : 0
TxDefer     : 0
TxLateCol   : 0

        pvid: 1
        link: port:1 link:down
Port 2:
        mib: Port 2 MIB counters
RxBroad     : 0
RxPause     : 0
RxMulti     : 0
RxFcsErr    : 0
RxAlignErr  : 0
RxRunt      : 0
RxFragment  : 0
Rx64Byte    : 0
Rx128Byte   : 0
Rx256Byte   : 0
Rx512Byte   : 0
Rx1024Byte  : 0
Rx1518Byte  : 0
RxMaxByte   : 0
RxTooLong   : 0
RxGoodByte  : 0
RxBadByte   : 0
RxOverFlow  : 0
Filtered    : 0
TxBroad     : 0
TxPause     : 0
TxMulti     : 0
TxUnderRun  : 0
Tx64Byte    : 0
Tx128Byte   : 0
Tx256Byte   : 0
Tx512Byte   : 0
Tx1024Byte  : 0
Tx1518Byte  : 0
TxMaxByte   : 0
TxOverSize  : 0
TxByte      : 0
TxCollision : 0
TxAbortCol  : 0
TxMultiCol  : 0
TxSingleCol : 0
TxExcDefer  : 0
TxDefer     : 0
TxLateCol   : 0

        pvid: 1
        link: port:2 link:down
Port 3:
        mib: Port 3 MIB counters
RxBroad     : 0
RxPause     : 0
RxMulti     : 0
RxFcsErr    : 0
RxAlignErr  : 0
RxRunt      : 0
RxFragment  : 0
Rx64Byte    : 0
Rx128Byte   : 0
Rx256Byte   : 0
Rx512Byte   : 0
Rx1024Byte  : 0
Rx1518Byte  : 0
RxMaxByte   : 0
RxTooLong   : 0
RxGoodByte  : 0
RxBadByte   : 0
RxOverFlow  : 0
Filtered    : 0
TxBroad     : 0
TxPause     : 0
TxMulti     : 0
TxUnderRun  : 0
Tx64Byte    : 0
Tx128Byte   : 0
Tx256Byte   : 0
Tx512Byte   : 0
Tx1024Byte  : 0
Tx1518Byte  : 0
TxMaxByte   : 0
TxOverSize  : 0
TxByte      : 0
TxCollision : 0
TxAbortCol  : 0
TxMultiCol  : 0
TxSingleCol : 0
TxExcDefer  : 0
TxDefer     : 0
TxLateCol   : 0

        pvid: 1
        link: port:3 link:down
Port 4:
        mib: Port 4 MIB counters
RxBroad     : 0
RxPause     : 0
RxMulti     : 0
RxFcsErr    : 0
RxAlignErr  : 0
RxRunt      : 0
RxFragment  : 0
Rx64Byte    : 0
Rx128Byte   : 0
Rx256Byte   : 0
Rx512Byte   : 0
Rx1024Byte  : 0
Rx1518Byte  : 0
RxMaxByte   : 0
RxTooLong   : 0
RxGoodByte  : 0
RxBadByte   : 0
RxOverFlow  : 0
Filtered    : 0
TxBroad     : 0
TxPause     : 0
TxMulti     : 0
TxUnderRun  : 0
Tx64Byte    : 0
Tx128Byte   : 0
Tx256Byte   : 0
Tx512Byte   : 0
Tx1024Byte  : 0
Tx1518Byte  : 0
TxMaxByte   : 0
TxOverSize  : 0
TxByte      : 0
TxCollision : 0
TxAbortCol  : 0
TxMultiCol  : 0
TxSingleCol : 0
TxExcDefer  : 0
TxDefer     : 0
TxLateCol   : 0

        pvid: 1
        link: port:4 link:down
Port 5:
        mib: Port 5 MIB counters
RxBroad     : 285
RxPause     : 0
RxMulti     : 13950
RxFcsErr    : 0
RxAlignErr  : 0
RxRunt      : 0
RxFragment  : 0
Rx64Byte    : 200
Rx128Byte   : 1167
Rx256Byte   : 2457
Rx512Byte   : 5228
Rx1024Byte  : 4916
Rx1518Byte  : 429
RxMaxByte   : 0
RxTooLong   : 0
RxGoodByte  : 6648413
RxBadByte   : 0
RxOverFlow  : 0
Filtered    : 8742
TxBroad     : 3
TxPause     : 0
TxMulti     : 16
TxUnderRun  : 0
Tx64Byte    : 3
Tx128Byte   : 32
Tx256Byte   : 14
Tx512Byte   : 2
Tx1024Byte  : 0
Tx1518Byte  : 0
TxMaxByte   : 0
TxOverSize  : 0
TxByte      : 6078
TxCollision : 0
TxAbortCol  : 0
TxMultiCol  : 0
TxSingleCol : 0
TxExcDefer  : 0
TxDefer     : 0
TxLateCol   : 0

        pvid: 2
        link: port:5 link:up speed:1000baseT full-duplex auto
VLAN 1:
        vid: 1
        ports: 0t 2 3 4
VLAN 2:
        vid: 2
        ports: 0 5`
```

```
root@OpenWrt:/# cat /etc/board.json
{
        "model": {
                "id": "aruba,ap-303h",
                "name": "Aruba AP-303H"
        },
        "network": {
                "lan": {
                        "device": "eth0",
                        "protocol": "static"
                },
                "wan": {
                        "device": "eth1",
                        "protocol": "dhcp"
                }
        },
        "switch": {
                "switch0": {
                        "enable": true,
                        "reset": true,
                        "ports": [
                                {
                                        "num": 0,
                                        "device": "eth0",
                                        "need_tag": false,
                                        "want_untag": true
                                },
                                {
                                        "num": 2,
                                        "role": "lan",
                                        "index": 1
                                },
                                {
                                        "num": 3,
                                        "role": "lan",
                                        "index": 2
                                },
                                {
                                        "num": 4,
                                        "role": "lan",
                                        "index": 3
                                },
                                {
                                        "num": 0,
                                        "device": "eth1",
                                        "need_tag": false,
                                        "want_untag": true
                                },
                                {
                                        "num": 5,
                                        "role": "wan"
                                }
                        ],
                        "roles": [
                                {
                                        "role": "lan",
                                        "ports": "2 3 4 0",
                                        "device": "eth0"
                                },
                                {
                                        "role": "wan",
                                        "ports": "5 0",
                                        "device": "eth1"
                                }
                        ]
                }
        }
}
```

</p>
</details>

### CODE REVIEW

**Comment by yogo1212** [comment]
build is running. will upload and then you can test :-)

**Comment by yogo1212** [comment]
@kroon040 
here's the image built from this PR:
https://www.file-upload.net/download-14876413/openwrt-ipq40xx-generic-aruba_ap-303h-squashfs-sysupgrade.bin.html

**Comment by kroon040** [comment]
thnx. I go try tomorrow and let you know.

**Comment by kroon040** [comment]
> @kroon040 here's the image built from this PR: https://www.file-upload.net/download-14876413/openwrt-ipq40xx-generic-aruba_ap-303h-squashfs-sysupgrade.bin.html

Hi, 

I first fllashed the original 22.01.2 image dan I there can connect to the mgmt and als the dhcp wan works, and uploaded your image, and kept the config. I also tried is with overwriting config.

The image boots , but I lost connectivity, on the wan dhcp not working and the lan ports I can't go to the management ip anymore. 

regards Richard

**Comment by kroon040** [comment]
Also one question. Do I need to change the config from 

`
config interface 'loopback'
        option device 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fdf4:e830:8a23::/48'

config device
        option name 'br-lan'
        option type 'bridge'
        list ports 'eth0'

config interface 'lan'
        option device 'br-lan'
        option proto 'static'
        option ipaddr '192.168.199.150'
        option netmask '255.255.255.0'
        option gateway '192.168.199.254'
        option ip6assign '60'

config interface 'wan'
        option device 'eth1'
        option proto 'dhcp'

config interface 'wan6'
        option device 'eth1'
        option proto 'dhcpv6'

config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '2 3 4 0'

config switch_vlan
        option device 'switch0'
        option vlan '2'
        option ports '5 0'
`

to this?

`
config interface 'loopback'
        option device 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fdf4:e830:8a23::/48'

config device
	option type 'bridge'
	option name 'br0'
	list ports 'lan1'
	list ports 'lan2'
	list ports 'lan3'
	list ports 'wan'

config interface 'lan'
        option device 'br-lan'
        option proto 'static'
        option ipaddr '192.168.199.150'
        option netmask '255.255.255.0'
        option gateway '192.168.199.254'
        option ip6assign '60'

config interface 'wan'
        option device 'eth1'
        option proto 'dhcp'

config interface 'wan6'
        option device 'eth1'
        option proto 'dhcpv6'

config bridge-vlan
	option device 'br0'
	option vlan '1'
	list ports 'lan1:u*'
	list ports 'lan2:u*'
	list ports 'lan3:u*'

config bridge-vlan
	option device 'br0'
	option vlan '2'
	list ports 'wan:u*'
`

**Comment by kroon040** [comment]
I changed the config to this, but no connectivity (can't ping )

`
config interface 'loopback'
        option device 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fd5c:3843:6804::/48'

config device
        option type 'bridge'
        option name 'br0'
        list ports 'lan1'
        list ports 'lan2'
        list ports 'lan3'

config interface 'lan'
        option device 'br0'
        option proto 'static'
        option ipaddr '192.168.199.150'
        option netmask '255.255.255.0'
        option netmask '192.168.199.254'
        option ip6assign '60'

config interface 'wan'
        option device 'eth1'
        option proto 'dhcp'

config interface 'wan6'
        option device 'eth1'
        option proto 'dhcpv6'

config bridge-vlan
        option device 'br0'
        option vlan '1'
        list ports 'lan1:u*'
        list ports 'lan2:u*'
        list ports 'lan3:u*'
`

**Comment by yogo1212** [comment]
@kroon040 the last config already looks a lot better.

I can see conflicting netmask definitions and the device `eth1` probably shouldn't be used (if it even exist).
The swconfig you posted doesn't use VLAN tags anywhere.
It looks to me as if bridge-vlan does pretty much the same thing as `br-lan` device - sending untagged packets on all lan ports.
Can you try without?

If I'm not missing something, this should cover everything the original configuration did:

```
config device
	option type 'bridge'
	option name 'br-lan'
	list ports 'lan1'
	list ports 'lan2'
	list ports 'lan3'

config interface 'lan'
	option device 'br-lan'
	option proto 'static'
	option ip6assign '60'
	option ipaddr '192.168.199.150/24'
	option gateway '192.168.199.254'

config interface 'wan'
	option device 'wan'
	option proto 'dhcp'

config interface 'wan6'
	option device '@wan'
	option proto 'dhcpv6'
```

If that doesn't work, could you please try `sysupgrade -n ..`?
The configuration generated by openwrt should work and if it doesn't, we know the image doesn't work at all.

**Comment by kroon040** [comment]
Hi,

I did again flash the normal image. Than I downloaded your bin on de tmp dir and did an sysupgrade -n ..

Than I reboot and added he config above  and rebooted again.

Now I have a connection. 

```
br-lan    Link encap:Ethernet  HWaddr 20:4C:03:23:64:0C
          inet addr:192.168.199.150  Bcast:192.168.199.255  Mask:255.255.255.0
          inet6 addr: fdc7:eaf6:d61c::1/60 Scope:Global
          inet6 addr: fe80::224c:3ff:fe23:640c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:23063 errors:0 dropped:289 overruns:0 frame:0
          TX packets:91 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:11155100 (10.6 MiB)  TX bytes:7498 (7.3 KiB)

eth0      Link encap:Ethernet  HWaddr 20:4C:03:23:64:0C
          inet6 addr: fe80::224c:3ff:fe23:640c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:23296 errors:0 dropped:0 overruns:0 frame:0
          TX packets:107 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:11521982 (10.9 MiB)  TX bytes:10043 (9.8 KiB)
          Base address:0x8000

lan1      Link encap:Ethernet  HWaddr 20:4C:03:23:64:0C
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:23296 errors:0 dropped:39 overruns:0 frame:0
          TX packets:91 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:11195838 (10.6 MiB)  TX bytes:7498 (7.3 KiB)

lan2      Link encap:Ethernet  HWaddr 20:4C:03:23:64:0C
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lan3      Link encap:Ethernet  HWaddr 20:4C:03:23:64:0C
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:360 errors:0 dropped:0 overruns:0 frame:0
          TX packets:360 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:27976 (27.3 KiB)  TX bytes:27976 (27.3 KiB)

wan       Link encap:Ethernet  HWaddr 20:4C:03:23:64:0C
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
root@OpenWrt:/# ping 192.168.199.254
PING 192.168.199.254 (192.168.199.254): 56 data bytes
64 bytes from 192.168.199.254: seq=0 ttl=64 time=0.669 ms


Now I want to add vlans to and uplink port, for example LAN 1 , untagged vlan99 (also primary vlan), and tagged 10 and 70.

The uplink is also configured like this (another openwrt device (aruba ap-105, works  with the vlans)

**Comment by yogo1212** [comment]
@kroon040 if adding the bridge-vlan breaks networking, you could try just creating regular old networks using `device='lan1.70'`

could you test whether all ethernet ports and have proper MAC addresses?
if they work, we can open this PR for review and have it merged.
configuration should better be discussed in the forums rather than on github :-)

**Comment by yogo1212** [comment]
@kroon040 i've had a case with the wpj428 where the network would die after adding the vlan.
it started working again after a reboot.

could you check whether that's the case for you as well?
(add the bridge-vlan, `/etc/init.d/network reload`, the router should cede any network activity, and resume after a reboot)

**Comment by kroon040** [comment]
Hi. I didn't see that last reply, but I alse noticed that het someone has a patched driver https://github.com/openwrt/openwrt/pull/4721

Can you also make an image with the patched ipq40xx driver, so I can test this? and that I also do a reload of the network

**Comment by yogo1212** [comment]
@kroon040 
build is running

**Comment by yogo1212** [comment]
Here's the result:
[ap303h_with_patch.tar.gz](https://github.com/sartura/openwrt/files/8524181/ap303h_with_patch.tar.gz)

**Comment by kroon040** [comment]
Thnx. I will test it later today.

Can you also build the aruba 303 with the patch. I also have this device and works with vlans but some clients  I noticed some delay and maybe this also soles with this patch

**Comment by kroon040** [comment]
Installed the image with the patch. And also no luck when adding vlans, that it stops working. Also did a restart of networking after boot, als no luck

**Comment by robimarko** [comment]
Hi, thanks for the PR.

DSA support for IPQ40xx has been merged into OpenWrt, so this PR should be opened against OpenWrt master now.
https://github.com/openwrt/openwrt

Regards,
Robert

**Pull request closed without merging**
