### PR TITLE
ipq40xx: convert GL-AP1300 to DSA

### PR DESCRIPTION
**Pull request by PolynomialDivision**
[openwrt-ipq40xx-generic-glinet_gl-ap1300-squashfs-nand-sysupgrade.zip](https://github.com/sartura/openwrt/files/9126105/openwrt-ipq40xx-generic-glinet_gl-ap1300-squashfs-nand-sysupgrade.zip)

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@robimarko As I understood, we have a ack from @bluewavenet

**Comment by bluewavenet** [comment]
@robimarko @PolynomialDivision 
Ack confirmed. Tested on hardware and found to be good.

**Comment by robimarko** [comment]
Hi, thanks for the PR.

DSA support for IPQ40xx has been merged into OpenWrt, so this PR should be opened against OpenWrt master now.
https://github.com/openwrt/openwrt

Regards,
Robert

**Comment by bluewavenet** [comment]
@PolynomialDivision 
Let me know if you need any further testing.

**Comment by PolynomialDivision** [comment]
@bluewavenet As I understood you the device was working? I would do the PR against OpenWrt repository and add you as `Tested-by: Rob White <rob@blue-wave.net>`?

**Comment by bluewavenet** [comment]
@PolynomialDivision 
Yes I can confirm that the image you posted here works. Should we test it built against current master or is that not necessary?

**Pull request closed without merging**
