### PR TITLE
DSA for WPJ428 (ipq40xx)

### PR DESCRIPTION
**Pull request by yogo1212**
huge thanks for your great work :pray: 

Signed-off-by: Leon M. George <leon@georgemail.eu>

### CODE REVIEW

**Comment by yogo1212** [comment]
test results:
the address assignment is correct.
there is no traffic through `lan1` (switch port 4) - investigating.

link detection works. traffic through `lan2` works.

**Comment by yogo1212** [comment]
`tcpdump -i wan` on the router yields:

```
18:06:15.058205 ARP, Reply 0.0.0.0 is-at 43:05:43:05:00:00, length 46
18:06:15.211956 19:21:68:01:23:45 > 00:b0:52:00:00:01, ethertype Unknown (0x88e1), length 60: 
        0x0000:  0068 a000 b052 486b f1bf 0000 0000 0000  .h...RHk........
        0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............
18:06:15.212347 19:21:68:01:23:45 > ff:ff:ff:ff:ff:ff, ethertype Unknown (0x88e1), length 60: 
        0x0000:  0000 a000 b052 486b f1bf 0000 0000 0000  .....RHk........
        0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............
18:06:15.212950 19:21:68:01:23:45 > ff:ff:ff:ff:ff:ff, ethertype Unknown (0x8912), length 60: 
        0x0000:  0170 a000 0000 1f84 6ba3 97a2 5553 bef1  .p......k...US..
        0x0010:  fcf9 796b 5214 13e9 e200 0000 0000 0000  ..ykR...........
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............
18:06:16.069643 ARP, Request who-has 192.168.0.1 tell 192.168.0.49, length 28
18:06:17.079312 ARP, Request who-has 192.168.0.1 tell 192.168.0.49, length 28
18:06:17.212747 19:21:68:01:23:45 > 00:b0:52:00:00:01, ethertype Unknown (0x88e1), length 60: 
        0x0000:  0068 a000 b052 486b f1bf 0000 0000 0000  .h...RHk........
        0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............
18:06:17.212944 19:21:68:01:23:45 > ff:ff:ff:ff:ff:ff, ethertype Unknown (0x88e1), length 60: 
        0x0000:  0000 a000 b052 486b f1bf 0000 0000 0000  .....RHk........
        0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............
18:06:17.213646 19:21:68:01:23:45 > ff:ff:ff:ff:ff:ff, ethertype Unknown (0x8912), length 60: 
        0x0000:  0170 a000 0000 1f84 6ba3 97a2 5553 bef1  .p......k...US..
        0x0010:  fcf9 796b 5214 13e9 e200 0000 0000 0000  ..ykR...........
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............
```

`19:21:68:01:23:45` being the default gateway.
The ethertypes are Fritzbox-related.

So traffic is going to the CPU and away from the CPU. But the switch that the WPJ428 is attached to sees no traffic coming from the corresponding port. No MAC for that port in the bridge's MAC table either..

**Comment by yogo1212** [comment]
And the culprit was.........

A broken lead.

I'd say this is ready for merge :-)

**Comment by yogo1212** [comment]
@robimarko is there something i should do here?

**Comment by robimarko** [comment]
Thanks, I just got a notification that you even made a PR.
If you say it works, I can just pick the commit and squash it into the conversion one.

**Comment by yogo1212** [comment]
It works :-)

Thank you for working on this - being able to use DSA with ipq4019 makes my life a lot easier!

**Comment by robimarko** [comment]
It's been added to the PR.
Thanks.

**Pull request closed without merging**
