### PR TITLE
Convert R619AC to DSA

### PR DESCRIPTION
**Pull request by PussAzuki**
Signed-off-by: PussAzuki <z1250747241@gmail.com>

Convert R619AC to DSA, already tested.

### CODE REVIEW

**Comment by robimarko** [comment]
Thanks, my only question is how the MAC-s are being set?

**Comment by PussAzuki** [comment]
> Thanks, my only question is how the MAC-s are being set?

The order of appearance of MAC in the ART partition is LAN, followed by WAN, then 5G WiFi, and finally 2.4G WiFi
MAC values are LAN LAN+1 LAN+2 LAN+3 using hexadecimal

**Comment by robimarko** [comment]
Thats fine, but how are they being set in OpenWrt, via which mechanism?
Cause, you dont use aliases so U-boot is no setting them, 02_network is not setting them and NVMEM is not used.

Also, please rebase and then squash

**Comment by PussAzuki** [comment]
All I know is that the hardware of this machine is exactly the same as qcom-ipq4019-ap.dk07.1-c1 under QSDK, but I can show you the following MAC examples.
[LAN & WAN MAC](https://user-images.githubusercontent.com/30948760/159240401-d96d99a9-c813-49eb-a3fe-3270548050ac.png)
[5G WiFi MAC](https://user-images.githubusercontent.com/30948760/159241026-de0c9cd8-dca0-4e43-aa5d-1687942b52df.png)
[2.4G WiFi MAC](https://user-images.githubusercontent.com/30948760/159241103-d10f2b02-3ce3-46a6-aa8f-9f3fc94bc6a9.png)

**Comment by robimarko** [comment]
I understand that, but what mechanism in OpenWrt is setting those MAC-s?
Cause, you don't use aliases so U-boot is not setting them, 02_network is not setting them and NVMEM is not used.

**Comment by PussAzuki** [comment]
I'm sorry, I don't know how it works either, I just thought I could help this PR and tried to take over.

```
&psgmii_phy {
	status = "okay";
};
```

Is this node required or optional? I see the above nodes appearing in the already merged PR, but there are actually no such nodes. 
🤔

**Comment by robimarko** [comment]
That node does not exist at all, feel free to drop it.

As far as MAC-s go, do they match the stock FW?

**Comment by PussAzuki** [comment]
They are supposed to correspond to the stock firmware, but I may have the MAC addresses of the 2.4G WiFi and 5G WiFi above backwards. I'm currently checking MAC addresses on a router with Qualcomm chips and stock firmware, and they are LAN WAN 2.4G 5G. So as the existence of a similar development board should not modify the need for this part.

But when I use `ip link` to check, I found that `wan@eth0` also uses the MAC of the LAN, is this the expected behavior when using the DSA driver?

**Pull request closed without merging**
